# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Unit rendering (golden) and install/uninstall against a fake systemctl."""

import pathlib

import pytest

from fx_updater import systemd


class FakeSystemd:
    """Records every command; answers each with a scripted return code."""

    def __init__(self, rcs=None):
        self.calls: list[list[str]] = []
        self.rcs = rcs or {}

    def __call__(self, cmd):
        self.calls.append(cmd)
        return self.rcs.get(" ".join(cmd[:3]), 0), ""


_SERVICE = """\
# Generated by fx-updater; `fx-updater uninstall` removes this file.
[Unit]
Description=fx-updater: update and build a Fuchsia checkout
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory=/src/fuchsia
ExecStart=/venv/bin/python -m fx_updater run --config /cfg/config.toml
TimeoutStartSec=5h
Nice=10
"""

_TIMER = """\
# Generated by fx-updater; `fx-updater uninstall` removes this file.
[Unit]
Description=fx-updater: scheduled update and build

[Timer]
OnCalendar=*-*-* 05:30:00
Persistent=true

[Install]
WantedBy=timers.target
"""

_ARGV = ["/venv/bin/python", "-m", "fx_updater", "run", "--config", "/cfg/config.toml"]


def test_service_golden():
    assert systemd.render_service(_ARGV, pathlib.Path("/src/fuchsia")) == _SERVICE


def test_timer_golden():
    assert systemd.render_timer("*-*-* 05:30:00") == _TIMER


def test_exec_args_are_escaped_for_systemd():
    text = systemd.render_service(
        ["/a b/python", "100%", 'say "hi"', "$HOME"], pathlib.Path("/t%h")
    )
    assert 'ExecStart="/a b/python" 100%% "say \\"hi\\"" "$$HOME"' in text
    # %h would expand to the home dir; a literal % must be doubled.
    assert "WorkingDirectory=/t%%h" in text


@pytest.mark.parametrize(
    "name, ok",
    [
        ("fx-updater", True),
        ("fx-updater-test", True),
        ("a b", False),
        ("../x", False),
        ("", False),
        ("-x", False),
    ],
)
def test_unit_name_validation(name, ok):
    assert systemd.valid_unit_name(name) is ok


def _install(tmp_path, fake, **kw):
    return systemd.install("fxu", _SERVICE, _TIMER, run=fake, directory=tmp_path, **kw)


def test_install_writes_units_then_reloads_then_enables(tmp_path):
    fake = FakeSystemd()
    actions = _install(tmp_path, fake)
    assert (tmp_path / "fxu.service").read_text() == _SERVICE
    assert (tmp_path / "fxu.timer").read_text() == _TIMER
    assert fake.calls == [
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", "--now", "fxu.timer"],
    ]
    assert actions == [
        f"write {tmp_path}/fxu.service",
        f"write {tmp_path}/fxu.timer",
        "systemctl --user daemon-reload",
        "systemctl --user enable --now fxu.timer",
    ]


def test_install_twice_converges_and_says_unchanged(tmp_path):
    _install(tmp_path, FakeSystemd())
    actions = _install(tmp_path, FakeSystemd())
    assert actions[:2] == [
        f"unchanged {tmp_path}/fxu.service",
        f"unchanged {tmp_path}/fxu.timer",
    ]


def test_install_rewrites_its_own_unit_when_it_changed(tmp_path):
    _install(tmp_path, FakeSystemd())
    new_timer = systemd.render_timer("*-*-* 03:00:00")
    systemd.install("fxu", _SERVICE, new_timer, run=FakeSystemd(), directory=tmp_path)
    assert (tmp_path / "fxu.timer").read_text() == new_timer


def test_install_never_clobbers_a_foreign_unit(tmp_path):
    (tmp_path / "fxu.timer").write_text("[Timer]\nOnCalendar=hourly\n")
    fake = FakeSystemd()
    with pytest.raises(systemd.UnitConflict):
        _install(tmp_path, fake)
    assert (tmp_path / "fxu.timer").read_text() == "[Timer]\nOnCalendar=hourly\n"
    assert not (tmp_path / "fxu.service").exists()
    assert not fake.calls


def test_install_dry_run_changes_nothing(tmp_path):
    fake = FakeSystemd()
    actions = _install(tmp_path, fake, dry_run=True)
    assert not list(tmp_path.iterdir())
    assert not fake.calls
    assert len(actions) == 4


def test_install_reports_a_failed_systemctl(tmp_path):
    fake = FakeSystemd({"systemctl --user enable": 1})
    with pytest.raises(systemd.SystemctlError) as e:
        _install(tmp_path, fake)
    assert e.value.returncode == 1
    assert e.value.changed is True


def test_install_failure_after_no_write_is_not_a_change(tmp_path):
    _install(tmp_path, FakeSystemd())
    with pytest.raises(systemd.SystemctlError) as e:
        _install(tmp_path, FakeSystemd({"systemctl --user enable": 1}))
    assert e.value.changed is False


def test_uninstall_disable_failure_changes_nothing(tmp_path):
    _install(tmp_path, FakeSystemd())
    with pytest.raises(systemd.SystemctlError) as e:
        systemd.uninstall(
            "fxu", run=FakeSystemd({"systemctl --user disable": 1}), directory=tmp_path
        )
    assert e.value.changed is False
    assert sorted(p.name for p in tmp_path.iterdir()) == ["fxu.service", "fxu.timer"]


def test_uninstall_reload_failure_after_removal_is_a_change(tmp_path):
    (tmp_path / "fxu.service").write_text(_SERVICE)
    with pytest.raises(systemd.SystemctlError) as e:
        systemd.uninstall(
            "fxu",
            run=FakeSystemd({"systemctl --user daemon-reload": 127}),
            directory=tmp_path,
        )
    assert e.value.changed is True


def test_missing_systemd_analyze_is_not_a_bad_schedule():
    with pytest.raises(systemd.SystemctlError) as e:
        systemd.check_calendar(lambda cmd: (127, "not found"), "daily")
    assert e.value.returncode == 127


@pytest.mark.parametrize(
    "render",
    [
        lambda: systemd.render_service(
            ["/py", "a\nExecStartPre=/x"], pathlib.Path("/t")
        ),
        lambda: systemd.render_service(["/py"], pathlib.Path("/t\n[Install]")),
        lambda: systemd.render_timer("daily\nOnBootSec=1"),
    ],
)
def test_a_newline_can_never_start_a_directive(render):
    with pytest.raises(ValueError):
        render()


def test_uninstall_disables_then_removes_then_reloads(tmp_path):
    _install(tmp_path, FakeSystemd())
    fake = FakeSystemd()
    actions = systemd.uninstall("fxu", run=fake, directory=tmp_path)
    assert not list(tmp_path.iterdir())
    assert fake.calls == [
        ["systemctl", "--user", "disable", "--now", "fxu.timer"],
        ["systemctl", "--user", "daemon-reload"],
    ]
    assert actions[0] == "systemctl --user disable --now fxu.timer"


def test_uninstall_when_nothing_is_installed_does_nothing(tmp_path):
    fake = FakeSystemd()
    assert not systemd.uninstall("fxu", run=fake, directory=tmp_path)
    assert not fake.calls


def test_uninstall_of_a_lone_service_skips_the_timer_disable(tmp_path):
    (tmp_path / "fxu.service").write_text(_SERVICE)
    fake = FakeSystemd()
    systemd.uninstall("fxu", run=fake, directory=tmp_path)
    assert fake.calls == [["systemctl", "--user", "daemon-reload"]]
    assert not (tmp_path / "fxu.service").exists()


def test_uninstall_never_removes_a_foreign_unit(tmp_path):
    _install(tmp_path, FakeSystemd())
    (tmp_path / "fxu.service").write_text("[Service]\nExecStart=/bin/true\n")
    fake = FakeSystemd()
    with pytest.raises(systemd.UnitConflict):
        systemd.uninstall("fxu", run=fake, directory=tmp_path)
    assert (tmp_path / "fxu.service").exists()
    assert (tmp_path / "fxu.timer").exists()
    assert not fake.calls


def test_uninstall_dry_run_changes_nothing(tmp_path):
    _install(tmp_path, FakeSystemd())
    fake = FakeSystemd()
    actions = systemd.uninstall("fxu", run=fake, directory=tmp_path, dry_run=True)
    assert sorted(p.name for p in tmp_path.iterdir()) == ["fxu.service", "fxu.timer"]
    assert not fake.calls
    assert len(actions) == 4


def test_linger_reads_loginctl():
    assert systemd.linger_enabled(lambda cmd: (0, "yes\n"), "u") is True
    assert systemd.linger_enabled(lambda cmd: (0, "no\n"), "u") is False
    assert systemd.linger_enabled(lambda cmd: (1, ""), "u") is None


def test_missing_binary_is_127():
    assert systemd.run_command(["/nonexistent/systemctl"])[0] == 127
