# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""systemd user units: render, install, uninstall.

`install` writes `<name>.service` and `<name>.timer` into the user unit dir,
reloads systemd and enables the timer. `uninstall` reverses it. Both are
idempotent: running either twice converges on the same state and says so.

Every unit file this module writes carries MARKER on its first line, and
neither operation touches a file of the same name that lacks it. A unit of
that name that someone wrote by hand is theirs, and overwriting or deleting
it would be a silent loss; refusing is loud and costs one `--unit-name`.

All `systemctl`/`loginctl`/`systemd-analyze` calls go through a `Runner`
(argv -> (returncode, output)) so tests can fake systemd entirely.
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import tempfile
from typing import Callable

MARKER = "# Generated by fx-updater; `fx-updater uninstall` removes this file."
DEFAULT_UNIT_NAME = "fx-updater"

Runner = Callable[[list[str]], tuple[int, str]]


class UnitConflict(Exception):
    """A unit file of this name exists and fx-updater did not write it."""


class SystemctlError(Exception):
    """A systemd command failed.

    `changed` says whether a unit file had already been written or removed
    when it failed, which is what separates "nothing done" from "partially
    done" for the caller.
    """

    def __init__(
        self, cmd: list[str], returncode: int, output: str, changed: bool = False
    ):
        super().__init__(f"{' '.join(cmd)} exited {returncode}: {output.strip()}")
        self.cmd = cmd
        self.returncode = returncode
        self.changed = changed


def run_command(cmd: list[str]) -> tuple[int, str]:
    """The real Runner. A missing binary is rc 127, like a shell would say."""
    try:
        done = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
            stdin=subprocess.DEVNULL,
        )
    except FileNotFoundError as e:
        return 127, str(e)
    return done.returncode, done.stdout + done.stderr


def unit_dir() -> pathlib.Path:
    """`$XDG_CONFIG_HOME/systemd/user`, else `~/.config/systemd/user`."""
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = pathlib.Path(xdg) if xdg else pathlib.Path.home() / ".config"
    return base / "systemd" / "user"


_UNIT_NAME_RE = re.compile(r"^[A-Za-z0-9:_.\\-]+$")


def valid_unit_name(name: str) -> bool:
    """A unit name without its suffix, per systemd's allowed characters."""
    return bool(_UNIT_NAME_RE.match(name)) and not name.startswith("-")


_SAFE_ARG_RE = re.compile(r"^[A-Za-z0-9_@%+=:,./-]+$")


def _exec_arg(arg: str) -> str:
    """One ExecStart= word: `%` and `$` escaped always, quoted when not plain.

    systemd expands `%h`-style specifiers and `$VAR` even inside quotes.
    """
    arg = arg.replace("%", "%%").replace("$", "$$")
    if _SAFE_ARG_RE.match(arg):
        return arg
    return '"' + arg.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _no_control_chars(*values: str) -> None:
    for value in values:
        if any(ord(c) < 0x20 or ord(c) == 0x7F for c in value):
            # A newline would end the directive and start another one.
            raise ValueError(f"control character in unit value {value!r}")


def render_service(exec_argv: list[str], working_dir: pathlib.Path) -> str:
    """The .service unit that runs one update-and-build."""
    _no_control_chars(*exec_argv, str(working_dir))
    return (
        f"{MARKER}\n"
        "[Unit]\n"
        "Description=fx-updater: update and build a Fuchsia checkout\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"WorkingDirectory={str(working_dir).replace('%', '%%')}\n"
        f"ExecStart={' '.join(_exec_arg(a) for a in exec_argv)}\n"
        # A cold build of a large product can take hours; the default 90 s
        # oneshot timeout would kill every real run.
        "TimeoutStartSec=5h\n"
        "Nice=10\n"
    )


def render_timer(schedule: str) -> str:
    """The .timer unit. Persistent= runs a missed slot at the next boot."""
    _no_control_chars(schedule)
    return (
        f"{MARKER}\n"
        "[Unit]\n"
        "Description=fx-updater: scheduled update and build\n"
        "\n"
        "[Timer]\n"
        f"OnCalendar={schedule}\n"
        "Persistent=true\n"
        "\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )


def _unit_paths(name: str, directory: pathlib.Path) -> list[pathlib.Path]:
    return [directory / f"{name}.service", directory / f"{name}.timer"]


def _refuse_foreign(paths: list[pathlib.Path]) -> None:
    for path in paths:
        if path.exists() and MARKER not in path.read_text(errors="replace"):
            raise UnitConflict(str(path))


def check_no_conflict(name: str, directory: pathlib.Path) -> None:
    """Raise UnitConflict if a unit of this name exists that we did not write.

    Callers that change other state first (the config file) call this before
    doing so, so a refused install changes nothing at all.
    """
    _refuse_foreign(_unit_paths(name, directory))


def _write_atomic(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        pathlib.Path(tmp).unlink(missing_ok=True)
        raise


def _systemctl(run: Runner, *args: str, changed: bool) -> None:
    cmd = ["systemctl", "--user", *args]
    rc, out = run(cmd)
    if rc != 0:
        raise SystemctlError(cmd, rc, out, changed=changed)


def check_available(run: Runner) -> None:
    """Raise SystemctlError (rc 127) if systemctl is not installed."""
    cmd = ["systemctl", "--version"]
    rc, out = run(cmd)
    if rc == 127:
        raise SystemctlError(cmd, rc, out)


def check_calendar(run: Runner, schedule: str) -> str | None:
    """None if systemd accepts `schedule` as an OnCalendar value, else why not.

    Raises SystemctlError (rc 127) when systemd-analyze is not installed:
    that is a missing tool, not a bad schedule.
    """
    cmd = ["systemd-analyze", "calendar", schedule]
    rc, out = run(cmd)
    if rc == 127:
        raise SystemctlError(cmd, rc, out)
    return None if rc == 0 else (out.strip() or f"systemd-analyze exited {rc}")


def linger_enabled(run: Runner, user: str) -> bool | None:
    """Whether the user's timers run while they are logged out; None if unknown."""
    rc, out = run(["loginctl", "show-user", user, "--property=Linger", "--value"])
    if rc != 0:
        return None
    return out.strip() == "yes"


def install(
    name: str,
    service: str,
    timer: str,
    *,
    run: Runner,
    directory: pathlib.Path,
    dry_run: bool = False,
) -> list[str]:
    """Write the units and enable the timer. Returns the actions, in order.

    Raises UnitConflict before changing anything if either file exists
    without MARKER, and SystemctlError if a systemd command fails.
    """
    paths = _unit_paths(name, directory)
    _refuse_foreign(paths)
    actions = []
    wrote = False
    for path, text in zip(paths, (service, timer)):
        if path.exists() and path.read_text() == text:
            actions.append(f"unchanged {path}")
            continue
        actions.append(f"write {path}")
        if not dry_run:
            _write_atomic(path, text)
            wrote = True
    actions.append("systemctl --user daemon-reload")
    actions.append(f"systemctl --user enable --now {name}.timer")
    if not dry_run:
        _systemctl(run, "daemon-reload", changed=wrote)
        _systemctl(run, "enable", "--now", f"{name}.timer", changed=wrote)
    return actions


def uninstall(
    name: str,
    *,
    run: Runner,
    directory: pathlib.Path,
    dry_run: bool = False,
) -> list[str]:
    """Disable the timer and remove both units. [] means nothing was installed.

    A run already in progress is left to finish: stopping the service would
    kill a build midway, and the next build would redo the work anyway.
    """
    paths = [p for p in _unit_paths(name, directory) if p.exists()]
    _refuse_foreign(paths)
    if not paths:
        return []
    actions = []
    if directory / f"{name}.timer" in paths:
        actions.append(f"systemctl --user disable --now {name}.timer")
        if not dry_run:
            # Disable before removing: systemd finds the enablement symlinks
            # through the unit file.
            _systemctl(run, "disable", "--now", f"{name}.timer", changed=False)
    for path in paths:
        actions.append(f"remove {path}")
        if not dry_run:
            path.unlink(missing_ok=True)
    actions.append("systemctl --user daemon-reload")
    if not dry_run:
        _systemctl(run, "daemon-reload", changed=True)
    return actions
